# Generated by Django 2.2.10 on 2020-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='title',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
