# Generated by Django 2.2.10 on 2020-05-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200530_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
