# Generated by Django 2.2.10 on 2020-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='place',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
