# Generated by Django 2.2.10 on 2020-05-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200530_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_or_univ', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('school_or_college', models.CharField(max_length=300)),
                ('cgpa_or_percent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.UserInfo')),
            ],
        ),
    ]
