# Generated by Django 2.2.10 on 2020-05-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200530_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='count',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
