# Generated by Django 2.2.10 on 2020-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_study_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='cgpa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='study',
            name='percent',
            field=models.BooleanField(default=False),
        ),
    ]
