# Generated by Django 2.2.10 on 2020-05-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='work_image',
            new_name='project_image',
        ),
        migrations.AddField(
            model_name='work',
            name='project_link',
            field=models.CharField(blank=True, max_length=2084, null=True),
        ),
    ]
