# Generated by Django 2.2.10 on 2020-05-31 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_userinfo_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='study',
            old_name='name',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='slug',
        ),
    ]
