# Generated by Django 2.2.10 on 2020-05-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200531_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
