# Generated by Django 2.2.10 on 2020-05-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200531_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('work_experience', models.TextField()),
                ('slug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.UserInfo')),
            ],
        ),
    ]
