# Generated by Django 2.2.10 on 2020-06-02 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='count',
        ),
    ]
