# Generated by Django 2.2.10 on 2020-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200603_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
