# Generated by Django 2.2.10 on 2020-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200605_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
