# Generated by Django 2.2.10 on 2020-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_experience_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ending_date',
            field=models.DateField(default='present'),
        ),
    ]
