# Generated by Django 2.2.10 on 2020-06-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20200605_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ending_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
